version: '3'

services:
  haskell:
    container_name: haskell
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/src
    logging:
      options:
        max-size: "500k"
    ports:
      - "50001:3000"
