version: "3"

services:
  python:
    container_name: python
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/src
    logging:
      driver: "json-file"
      options:
        max-size: "50k"
    ports:
      - "50001:3000"
