version: "3"

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    depends_on:
      - php
    logging:
      driver: "json-file"
      options:
        max-size: "50k"
    ports:
      - "50001:80"
  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src/:/var/www/html/
